//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLETAEXPERIMENTO
    {
        public int CODI_COE { get; set; }
        public int CODI_EXP { get; set; }
        public string TRATAM_COE { get; set; }
        public string REPETI_COE { get; set; }
        public System.DateTime DATCOL_COE { get; set; }
        public string ESTADI_COE { get; set; }
        public Nullable<int> INDIUV_COE { get; set; }
        public Nullable<decimal> PRESSA_COE { get; set; }
        public Nullable<int> PONORV_COE { get; set; }
        public Nullable<decimal> TEMMAX_COE { get; set; }
        public Nullable<decimal> TEMMIN_COE { get; set; }
        public Nullable<decimal> PLUVIO_COE { get; set; }
        public Nullable<decimal> VELVEN_COE { get; set; }
        public Nullable<int> UMIDAD_COE { get; set; }
        public Nullable<decimal> TENSIO_COE { get; set; }
        public Nullable<decimal> IRRQNT_COE { get; set; }
        public string VALRE1_EXP { get; set; }
        public string VALRE2_EXP { get; set; }
        public string VALRE3_EXP { get; set; }
        public string VALRE4_EXP { get; set; }
        public string VALRE5_EXP { get; set; }
        public string VALRE6_EXP { get; set; }
        public string VALRE7_EXP { get; set; }
        public string VALRE8_EXP { get; set; }
        public string VALRE9_EXP { get; set; }
        public string VALREA_EXP { get; set; }
        public string OBSGER_COE { get; set; }
    
        public virtual EXPERIMENTO EXPERIMENTO { get; set; }
    }
}
