//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLETAGERMINACAO
    {
        public int CODI_COG { get; set; }
        public int CODI_GER { get; set; }
        public string TRATAM_COG { get; set; }
        public string REPETI_COG { get; set; }
        public int PLAACO_COG { get; set; }
        public System.DateTime DATCOG_COG { get; set; }
        public int SEMGER_COG { get; set; }
        public int NAOGER_COG { get; set; }
        public Nullable<decimal> PORGER_COG { get; set; }
    
        public virtual GERMINACAO GERMINACAO { get; set; }
    }
}
