//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETICAO
    {
        public int CODI_COM { get; set; }
        public int CODI_CUL { get; set; }
        public string NOMECO_COM { get; set; }
        public int CODI_EXP { get; set; }
    
        public virtual CULTURA CULTURA { get; set; }
        public virtual EXPERIMENTO EXPERIMENTO { get; set; }
    }
}
