//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CULTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CULTURA()
        {
            this.COMPETICAO = new HashSet<COMPETICAO>();
            this.GERMINACAO = new HashSet<GERMINACAO>();
        }
    
        public int CODI_CUL { get; set; }
        public string NOMCUL_CUL { get; set; }
        public string CULTIV_CUL { get; set; }
        public string LOTECU_CUL { get; set; }
        public Nullable<decimal> GERMIN_CUL { get; set; }
        public Nullable<decimal> PUREZA_CUL { get; set; }
        public Nullable<System.DateTime> VALIDA_CUL { get; set; }
        public string SAFRAC_CUL { get; set; }
        public Nullable<decimal> M100SE_CUL { get; set; }
        public string TRAQUI_CUL { get; set; }
        public string PROSEM_CUL { get; set; }
        public string OBSERV_CUL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETICAO> COMPETICAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GERMINACAO> GERMINACAO { get; set; }
    }
}
