//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPERIMENTO()
        {
            this.COLETAEXPERIMENTO = new HashSet<COLETAEXPERIMENTO>();
            this.COMPETICAO = new HashSet<COMPETICAO>();
            this.GERMINACAO = new HashSet<GERMINACAO>();
        }
    
        public int CODI_EXP { get; set; }
        public int CODI_PRO { get; set; }
        public string CODI_COM { get; set; }
        public Nullable<int> NUMTRA_EXP { get; set; }
        public Nullable<int> NUMREP_EXP { get; set; }
        public Nullable<System.DateTime> DATINI_EXP { get; set; }
        public Nullable<decimal> DIAVAS_EXP { get; set; }
        public string DESTRA_EXP { get; set; }
        public int CODI_PAD { get; set; }
        public string EXPFIN_EXP { get; set; }
        public string TIPTRA_EXP { get; set; }
        public Nullable<decimal> PEIEA1_EXP { get; set; }
        public Nullable<decimal> PEIEA2_EXP { get; set; }
        public Nullable<decimal> PEIEA3_EXP { get; set; }
        public Nullable<decimal> PEQET1_EXP { get; set; }
        public Nullable<decimal> PEQET2_EXP { get; set; }
        public Nullable<decimal> PEQET3_EXP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLETAEXPERIMENTO> COLETAEXPERIMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETICAO> COMPETICAO { get; set; }
        public virtual NOMEPADRAOVARIAVEIS NOMEPADRAOVARIAVEIS { get; set; }
        public virtual PROPRIEDADE PROPRIEDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GERMINACAO> GERMINACAO { get; set; }
    }
}
