//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GERMINACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GERMINACAO()
        {
            this.COLETAGERMINACAO = new HashSet<COLETAGERMINACAO>();
        }
    
        public int CODI_GER { get; set; }
        public Nullable<int> CODI_EXP { get; set; }
        public int CODI_USU { get; set; }
        public string CODI_RES { get; set; }
        public int CODI_CUL { get; set; }
        public string ESPECI_GER { get; set; }
        public System.DateTime DATAMO_GER { get; set; }
        public int NUMTRA_GER { get; set; }
        public int NUMREP_GER { get; set; }
        public decimal PEPAGE_GER { get; set; }
        public decimal TEMPET_GER { get; set; }
        public Nullable<decimal> QUAGUA_GER { get; set; }
        public int QSETOT_GER { get; set; }
        public int QSEREP_GER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLETAGERMINACAO> COLETAGERMINACAO { get; set; }
        public virtual CULTURA CULTURA { get; set; }
        public virtual EXPERIMENTO EXPERIMENTO { get; set; }
    }
}
