//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProAgroEntities : DbContext
    {
        public ProAgroEntities()
            : base("name=ProAgroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLETAEXPERIMENTO> COLETAEXPERIMENTO { get; set; }
        public virtual DbSet<COLETAGERMINACAO> COLETAGERMINACAO { get; set; }
        public virtual DbSet<COMPETICAO> COMPETICAO { get; set; }
        public virtual DbSet<CULTURA> CULTURA { get; set; }
        public virtual DbSet<EXPERIMENTO> EXPERIMENTO { get; set; }
        public virtual DbSet<GERMINACAO> GERMINACAO { get; set; }
        public virtual DbSet<NOMEPADRAOVARIAVEIS> NOMEPADRAOVARIAVEIS { get; set; }
        public virtual DbSet<PROPRIEDADE> PROPRIEDADE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
