//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMEPADRAOVARIAVEIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOMEPADRAOVARIAVEIS()
        {
            this.EXPERIMENTO = new HashSet<EXPERIMENTO>();
        }
    
        public int CODI_PAD { get; set; }
        public string LAVAR1_PRO { get; set; }
        public string LAVAR2_PRO { get; set; }
        public string LAVAR3_PRO { get; set; }
        public string LAVAR4_PRO { get; set; }
        public string LAVAR5_PRO { get; set; }
        public string LAVAR6_PRO { get; set; }
        public string LAVAR7_PRO { get; set; }
        public string LAVAR8_PRO { get; set; }
        public string LAVAR9_PRO { get; set; }
        public string LAVARA_PRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPERIMENTO> EXPERIMENTO { get; set; }
    }
}
