//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPRIEDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPRIEDADE()
        {
            this.EXPERIMENTO = new HashSet<EXPERIMENTO>();
        }
    
        public int CODI_PRO { get; set; }
        public string NOMEPR_PRO { get; set; }
        public string MUNICI_PRO { get; set; }
        public string ESTADO_PRO { get; set; }
        public string ENDERE_PRO { get; set; }
        public string COMPLE_PRO { get; set; }
        public string TELEFO_PRO { get; set; }
        public string EMAILP_PROP { get; set; }
        public string NOMRES_PRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPERIMENTO> EXPERIMENTO { get; set; }
    }
}
