//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronomia
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CODI_USU { get; set; }
        public string LOGIN_USU { get; set; }
        public string SENHA_USU { get; set; }
        public string NOME_USU { get; set; }
        public string ENDERECO_USU { get; set; }
        public string TELEFONE_USU { get; set; }
        public string BAIRRO_USU { get; set; }
        public string COMPLEMENTO_USU { get; set; }
        public string CEP_USU { get; set; }
        public string ESTADO_USU { get; set; }
        public string STATUS { get; set; }
        public string USUADM { get; set; }
    }
}
