/*
 * Vmflex_websyncAboutBox.java
 */

package onlinestore_sync;

import main_application.Config;
import org.jdesktop.application.Action;

public class Onlinestore_syncSincBox extends javax.swing.JDialog {

    Config config = new Config();
    
    public Onlinestore_syncSincBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        //jCheckBox1.setSelected( config.getSyncElemDescontos().equals("1") );
        jCheckBox2.setSelected( config.getSyncElemEncomendas().equals("1") );
        //jCheckBox3.setSelected( config.getSyncElemClientes().equals("1") );
        jCheckBox4.setSelected( config.getSyncElemFamilias().equals("1") );
        jCheckBox5.setSelected( config.getSyncElemArtigos().equals("1") );
        //jCheckBox6.setSelected( config.getSyncElemEstadoEncomendas().equals("1") );
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(onlinestore_sync.Onlinestore_syncApp.class).getContext().getResourceMap(Onlinestore_syncSincBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(onlinestore_sync.Onlinestore_syncApp.class).getContext().getActionMap(Onlinestore_syncSincBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jCheckBox4.setText(resourceMap.getString("jCheckBox4.text")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        jCheckBox5.setText(resourceMap.getString("jCheckBox5.text")); // NOI18N
        jCheckBox5.setName("jCheckBox5"); // NOI18N

        jButton1.setAction(actionMap.get("GravaSincElem")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 317, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(84, 84, 84)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox4))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void GravaSincElem() {
//        if(jCheckBox1.isSelected()) {
//            config.setSyncElemDescontos("1");
//        }
//        else {
//            config.setSyncElemDescontos("0");
//        }
        
        if(jCheckBox2.isSelected()) {
            config.setSyncElemEncomendas("1");
        }
        else {
            config.setSyncElemEncomendas("0");
        }
        
//        if(jCheckBox3.isSelected()) {
//            config.setSyncElemClientes("1");
//        }
//        else {
//            config.setSyncElemClientes("0");
//        }
        
        if(jCheckBox4.isSelected()) {
            config.setSyncElemFamilias("1");
        }
        else {
            config.setSyncElemFamilias("0");
        }
        
        if(jCheckBox5.isSelected()) {
            config.setSyncElemArtigos("1");
        }
        else {
            config.setSyncElemArtigos("0");
        }
        
//        if(jCheckBox6.isSelected()) {
//            config.setSyncElemEstadoEncomendas("1");
//        }
//        else {
//            config.setSyncElemEstadoEncomendas("0");
//        }
        
        config.save();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    // End of variables declaration//GEN-END:variables
    
}
