//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCSAFTReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCSAFTReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema xmlns:doc=&quot;urn:schemas-basda-org:schema-extensions:documentation&quot; xmlns:ns=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.01_01&quot; xmlns=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.01_01&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.01_01&quot; version=&quot;1.01_01&quot; id=&quot;SAF-T_PT&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;doc:Title&gt;Standard Audit File - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsd_01_geral {
            get {
                return ResourceManager.GetString("xsd_01_geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema xmlns:doc=&quot;urn:schemas-basda-org:schema-extensions:documentation&quot; xmlns:ns=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.01_01&quot; xmlns=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.01_01&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.01_01&quot; version=&quot;1.01_01&quot; id=&quot;SAF-T_PT&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;doc:Title&gt;Standard Audit File - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsd_01_simplificado {
            get {
                return ResourceManager.GetString("xsd_01_simplificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;Windows-1252&apos;?&gt;
        ///&lt;xs:schema xmlns:doc=&apos;urn:schemas-basda-org:schema-extensions:documentation&apos; xmlns:ns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.02_01&apos; xmlns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.02_01&apos; attributeFormDefault=&apos;unqualified&apos; elementFormDefault=&apos;qualified&apos; targetNamespace=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.02_01&apos; version=&apos;1.02_01&apos; id=&apos;SAF-T_PT&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;doc:Title&gt;Standard Audit File - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsd_02_geral {
            get {
                return ResourceManager.GetString("xsd_02_geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;Windows-1252&apos;?&gt;
        ///&lt;xs:schema xmlns:doc=&apos;urn:schemas-basda-org:schema-extensions:documentation&apos; xmlns:ns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.02_01&apos; xmlns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.02_01&apos; attributeFormDefault=&apos;unqualified&apos; elementFormDefault=&apos;qualified&apos; targetNamespace=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.02_01&apos; version=&apos;1.02_01&apos; id=&apos;SAF-T_PT&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;doc:Title&gt;Standard Audit File - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsd_02_simplificado {
            get {
                return ResourceManager.GetString("xsd_02_simplificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;Windows-1252&apos;?&gt;
        ///&lt;xs:schema xmlns:doc=&apos;urn:schemas-basda-org:schema-extensions:documentation&apos; xmlns:ns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.03_01&apos; xmlns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.03_01&apos; attributeFormDefault=&apos;unqualified&apos; elementFormDefault=&apos;qualified&apos; targetNamespace=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.03_01&apos; version=&apos;1.03_01&apos; id=&apos;SAF-T_PT&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;doc:Title&gt;Standard Audit File - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsd_03_geral {
            get {
                return ResourceManager.GetString("xsd_03_geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;Windows-1252&apos;?&gt;
        ///&lt;xs:schema xmlns:doc=&apos;urn:schemas-basda-org:schema-extensions:documentation&apos; xmlns:ns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.03_01&apos; xmlns=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.03_01&apos; attributeFormDefault=&apos;unqualified&apos; elementFormDefault=&apos;qualified&apos; targetNamespace=&apos;urn:OECD:StandardAuditFile-Tax:PT_1.03_01&apos; version=&apos;1.03_01&apos; id=&apos;SAF-T_PT&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;doc:Title&gt;Standard Audit File - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsd_03_simplificado {
            get {
                return ResourceManager.GetString("xsd_03_simplificado", resourceCulture);
            }
        }
    }
}
