// <auto-generated />
namespace App_no_database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADICIONATELEFONEESTUDANTE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADICIONATELEFONEESTUDANTE));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161744369_ADICIONA-TELEFONE-ESTUDANTE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
